### PR TITLE
Lcd integration

### PR DESCRIPTION
**Pull request by pringon**
Had to fix some merge issues. Changes can be seen in the last 2 commits.

### CODE REVIEW

**Review by CarlosPurchase-Galarza — CHANGES_REQUESTED** [review]
change line 52 to:
font = ImageFont.truetype('/root/font.tff', 23)

**Comment by pringon** [comment]
I have made the change, should I try adding environment variables that allow us to select the path to the font? I can look into how to do that and come back with some resources we can base our discussion on.

**Comment by pringon** [comment]
I think that the solution in 044b14f7c0bebb78152114632b88a99fea5eb5df might work. It still however needs testing before we merge it into master.
@CarlosPurchase-Galarza @geofm61 can I get some feedback on this? I don't have a pi nor an lcd available at the moment so I can't do any testing. It would be great if you guys were able to, if not we can do it in labs tomorrow.

**Review by CarlosPurchase-Galarza — APPROVED** [review]

**Comment by CarlosPurchase-Galarza** [comment]
testing stuff now but most of it is making sure I have all the modules installed on the OS. I have no adc setup either so can't get values.

Also, can you look at line 10 of main

**Comment by pringon** [comment]
There isn't much purpose of keeping this alive now that the project is over.

**Pull request closed without merging**
